file=open("tops1.txt","w")
file.write("This is file management demo using python.")
file.close()
print("File Written Successfully")
print("*"*60)

file=open("tops1.txt","r")
print(file.read())
file.close()
print("*"*60)

file=open("tops1.txt","a")
file.write("\nThis file is now appended")
file.close()
print("*"*60)

file=open("tops1.txt","r")
print(file.read())
file.close()
print("*"*60)

file=open("tops2.txt","w+")
file.write("This is w+ mode using file management.")
print("Current File Position : ",file.tell())
file.seek(0)
print(file.read())
file.close()
print("*"*60)
